//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP.Plankton.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseZoomPreview {
            get {
                return ((bool)(this["UseZoomPreview"]));
            }
            set {
                this["UseZoomPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseAutoPanOnZoomPreview {
            get {
                return ((bool)(this["UseAutoPanOnZoomPreview"]));
            }
            set {
                this["UseAutoPanOnZoomPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double MaximumZoom {
            get {
                return ((double)(this["MaximumZoom"]));
            }
            set {
                this["MaximumZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double MinimumZoom {
            get {
                return ((double)(this["MinimumZoom"]));
            }
            set {
                this["MinimumZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double AutoPanSpeed {
            get {
                return ((double)(this["AutoPanSpeed"]));
            }
            set {
                this["AutoPanSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double AutoPanSensitivity {
            get {
                return ((double)(this["AutoPanSensitivity"]));
            }
            set {
                this["AutoPanSensitivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RefreshTime {
            get {
                return ((int)(this["RefreshTime"]));
            }
            set {
                this["RefreshTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseEfficientValuesWhenRandomGenerating {
            get {
                return ((bool)(this["UseEfficientValuesWhenRandomGenerating"]));
            }
            set {
                this["UseEfficientValuesWhenRandomGenerating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSmoothMousePositionUpdating {
            get {
                return ((bool)(this["UseSmoothMousePositionUpdating"]));
            }
            set {
                this["UseSmoothMousePositionUpdating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double ZoomPreviewSize {
            get {
                return ((double)(this["ZoomPreviewSize"]));
            }
            set {
                this["ZoomPreviewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IfMainBubbleNotAvailablePreviewMostInterestingElement {
            get {
                return ((bool)(this["IfMainBubbleNotAvailablePreviewMostInterestingElement"]));
            }
            set {
                this["IfMainBubbleNotAvailablePreviewMostInterestingElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOnlyStandardBrushesWhenRandomGenerating {
            get {
                return ((bool)(this["UseOnlyStandardBrushesWhenRandomGenerating"]));
            }
            set {
                this["UseOnlyStandardBrushesWhenRandomGenerating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AnythingButMainBubble")]
        public string ZoomPreviewLocatorMode {
            get {
                return ((string)(this["ZoomPreviewLocatorMode"]));
            }
            set {
                this["ZoomPreviewLocatorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCurrentIndicator {
            get {
                return ((bool)(this["ShowCurrentIndicator"]));
            }
            set {
                this["ShowCurrentIndicator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseAnimation {
            get {
                return ((bool)(this["UseAnimation"]));
            }
            set {
                this["UseAnimation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MaintainStandardPhysicsWhenRandomGeneratingSettings {
            get {
                return ((bool)(this["MaintainStandardPhysicsWhenRandomGeneratingSettings"]));
            }
            set {
                this["MaintainStandardPhysicsWhenRandomGeneratingSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseZoomPreviewBlurEffect {
            get {
                return ((bool)(this["UseZoomPreviewBlurEffect"]));
            }
            set {
                this["UseZoomPreviewBlurEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double MaximumZoomPreviewBlur {
            get {
                return ((double)(this["MaximumZoomPreviewBlur"]));
            }
            set {
                this["MaximumZoomPreviewBlur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ZoomPreviewBlurStrength {
            get {
                return ((double)(this["ZoomPreviewBlurStrength"]));
            }
            set {
                this["ZoomPreviewBlurStrength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double ZoomPreviewBlurCorrection {
            get {
                return ((double)(this["ZoomPreviewBlurCorrection"]));
            }
            set {
                this["ZoomPreviewBlurCorrection"] = value;
            }
        }
    }
}
